import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "../(dashboard)/_components/Header";
import Navbar from "../(dashboard)/_components/Navbar";

export const metadata: Metadata = {
  title: "SuperBudget | Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-tremor-background-muted min-h-screen flex flex-col">
        <div className="p-4 flex-1 flex flex-col-reverse justify-between md:justify-start md:flex-row h-full">
          <aside className="p-4 rounded-lg bg-slate-700 ">
            <Navbar />
          </aside>

          <div className="w-full sm:p-10 max-w-[1200px]">
            <Header />
            <main className="flex-1 bg-tremor-background-muted rounded-lg ">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
