import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "../(dashboard)/_components/Header";
import Navbar from "../(dashboard)/_components/Navbar";

export const metadata: Metadata = {
  title: "Supabudget | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-tremor-background-muted flex flex-col sm:flex-row p-4  min-h-screen">
        <aside>
          <Navbar />
        </aside>

        <div className="w-full p-10 ">
          <Header />
          <main className="flex-1 bg-tremor-background-muted rounded-lg ">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
